name: CI

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Get Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn build
      - uses: crazy-max/ghaction-github-pages@v3
        if: success()
        with:
          target_branch: gh-pages
          build_dir: build
          fqdn: opentempus.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}